# Generated by Django 5.1.2 on 2024-10-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_category_created_category_updated_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="media/products/%Y/%m/%d"
            ),
        ),
    ]
